### PR TITLE
feat: v0.0.7

### PR DESCRIPTION
**Pull request by shoriwe**

### CODE REVIEW

**Review by PedroChaparro — APPROVED** [review]
Just to let you know, I got the following error while trying to run the go app in my computer: 

```bash
/.../authentication-go/go.mod:3: invalid go version '1.21.0': must match format 1.23
```

It worked when I changed the version to `1.21` instead of `1.21.0` in the `go.mod` file, anyways, I think it's not an important error.

**Comment by shoriwe** [comment]
> Just to let you know, I got the following error while trying to run the go app in my computer:
> 
> ```shell
> /.../authentication-go/go.mod:3: invalid go version '1.21.0': must match format 1.23
> ```
> 
> It worked when I changed the version to `1.21` instead of `1.21.0` in the `go.mod` file, anyways, I think it's not an important error.

Thanks @PedroChaparro could you please confirm to me your installed go version by running:

```shell
go version
```

That error shouldn't happen, since the `go.mod` was created by built in `go mod init ...`

**Comment by PedroChaparro** [comment]
> Thanks @PedroChaparro could you please confirm to me your installed go version by running:

go1.19.4 linux/amd64

**Comment by shoriwe** [comment]
> > Thanks @PedroChaparro could you please confirm to me your installed go version by running:
> 
> go1.19.4 linux/amd64

Ok, that's it, try installing a newer version directly from Go's web page, package manager usually have older packages for Go.
Thanks!

**Pull request merged**
